production:
  cloud_name: "hmwo0k2zr"
  api_key: "329379665676472"
  api_secret: "Vl2lTMaE685Hv_vKoUmPtSIL_rU"


development:
  cloud_name: "hmwo0k2zr"
  api_key: "329379665676472"
  api_secret: "Vl2lTMaE685Hv_vKoUmPtSIL_rU"
